name: "Package: Backend"

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "packages/backend/**"
  pull_request:
    paths:
      - "packages/backend/**"

env:
  NODE_VERSION: "12.x"

jobs:
  backend:
    name: Checks (build, lint, tests)
    runs-on: ubuntu-latest
    env:
      FOLDER: packages/backend
      COVERAGE_FOLDER: packages/backend/coverage
      REPORTS_FOLDER: packages/backend/reports
      BUILD_FOLDER: packages/backend/dist
      PACKAGE: backend
      CODECOV_CONFIG: ./codecov.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Check cache of yarn dependencies
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn workspace $PACKAGE build

      - name: Lint project
        run: yarn workspace $PACKAGE lint:ci

      - name: Run unit tests with coverage
        run: yarn workspace $PACKAGE test:ci

      - name: Upload unit tests coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ env.COVERAGE_FOLDER }}/ut/lcov.info
          flags: unit
          yml: ${{ env.CODECOV_CONFIG }}
          fail_ci_if_error: true

      - name: Run End-to-End tests with coverage
        run: yarn workspace $PACKAGE e2e:ci

      - name: Upload End-to-End tests coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ env.COVERAGE_FOLDER }}/e2e/lcov.info
          flags: e2e
          yml: ${{ env.CODECOV_CONFIG }}
          fail_ci_if_error: true

      - name: Upload coverage reports
        uses: actions/upload-artifact@v1
        with:
          name: backend-coverage
          path: ${{ env.COVERAGE_FOLDER }}

      - name: Upload tests reports
        uses: actions/upload-artifact@v1
        with:
          name: backend-reports
          path: ${{ env.REPORTS_FOLDER }}

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: backend-build
          path: ${{ env.BUILD_FOLDER }}
